title:          Batik Gaming
description:    "Stop bermain judi slot. Mainkan permainan slot demo gratis tanpa deposit atau memakai uang asli."
baseurl:        "/"
url:            "https://batikgaming.github.io/"
markdown: kramdown
future: true
encoding: UTF-8
locales: ["id", "en"]
include:
  - _pages

language_default: id
collections_dir: content
collections:
  id:
    output: true
    permalink: /:collection/:slug
  en:
    output: true
    permalink: /:collection/:slug

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "id"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "en"
    values:
      layout: "page"



