title:          Batik Gaming
description:    "Stop bermain judi slot. Mainkan permainan slot demo gratis tanpa deposit atau memakai uang asli."
baseurl:        "/"
url:            "https://batikgaming.github.io/"
markdown: kramdown
future: true
encoding: UTF-8
include:
  - _pages


